{% set name = "social-analyzer" %}
{% set version = "0.44" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/social-analyzer-{{ version }}.tar.gz
  sha256: 87b7b0b0d9829183151966b0691565ad4a5c886e09e72b059c5ef8e15f839a31

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4
    - langdetect
    - lxml
    - python
    - requests
    - termcolor
    - tld
    - galeodes

test:
  commands:
    - pip check
    - social-analyzer --help
  requires:
    - pip

about:
  home: https://github.com/qeeqbox/social-analyzer
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: API, CLI & Web App for analyzing & finding a persons profile across +900 social media \ websites (Detections are updated regularly)
  description: |
    Social Analyzer - API, CLI & Web App for analyzing & finding a 
    person's profile across +900 social media \ websites. It includes
    different string analysis and detection modules, you can choose which
    combination of modules to use during the investigation process.
  doc_url: https://github.com/qeeqbox/social-analyzer/wiki
  dev_url: https://github.com/qeeqbox/social-analyzer

extra:
  recipe-maintainers:
    - jan-janssen
