{% set name = "social-analyzer" %}
{% set version = "0.38" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/social-analyzer-{{ version }}.tar.gz
  sha256: 17146958e326972e346f0cd6f595c4063fce42edf61cc32acf935817818cf963

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4
    - langdetect
    - lxml
    - python
    - requests
    - termcolor
    - tld

test:
  commands:
    - pip check
    - social-analyzer --help
  requires:
    - pip

about:
  home: https://github.com/qeeqbox/social-analyzer
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: API, CLI & Web App for analyzing & finding a persons profile across +900 social media \ websites (Detections are updated regularly)
  description: |
    Social Analyzer - API, CLI & Web App for analyzing & finding a 
    person's profile across +900 social media \ websites. It includes
    different string analysis and detection modules, you can choose which
    combination of modules to use during the investigation process.
  doc_url: https://github.com/qeeqbox/social-analyzer/wiki
  dev_url: https://github.com/qeeqbox/social-analyzer

extra:
  recipe-maintainers:
    - jan-janssen
