schema_version: 1

context:
  name: social-analyzer
  version: "0.45"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/social-analyzer-${{ version }}.tar.gz
  sha256: 1981e71d05d7c780f01697af586681d67b00308e0912f8a299a49fa1993636a3

build:
  number: 7
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - beautifulsoup4
    - langdetect
    - lxml
    - python
    - requests
    - termcolor
    - tld
    - galeodes

tests:
  - requirements:
      run:
        - pip
    script:
      - pip check
      - social-analyzer --help

about:
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: API, CLI & Web App for analyzing & finding a persons profile across +900 social media \ websites (Detections are updated regularly)
  description: |
    Social Analyzer - API, CLI & Web App for analyzing & finding a
    person's profile across +900 social media \ websites. It includes
    different string analysis and detection modules, you can choose which
    combination of modules to use during the investigation process.
  homepage: https://github.com/qeeqbox/social-analyzer
  repository: https://github.com/qeeqbox/social-analyzer
  documentation: https://github.com/qeeqbox/social-analyzer/wiki

extra:
  recipe-maintainers:
    - jan-janssen
